#!/usr/bin/env python3
"""Generate docs/vocabulary/*.md from data/vocab.tsv.

data/vocab.tsv is the single source of truth for words. This script renders:
  docs/vocabulary/index.md      full list, Armenian alphabetical order, topic links
  docs/vocabulary/<topic>.md    one page per topic tag that has words
Pages carry a GENERATED marker and are overwritten on every run. Never edit them by hand.
Also validates the TSV (unique ids, integer lessons, known part-of-speech tag first).
"""
from __future__ import annotations

import csv
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data" / "vocab.tsv"
OUT = ROOT / "docs" / "vocabulary"
MARKER = "<!-- GENERATED by scripts/build_vocab_pages.py from data/vocab.tsv — do not edit -->"

COLS = ["id", "hy", "en", "phrase_hy", "phrase_en", "lesson", "tags", "note"]
POS = {"noun", "verb", "adjective", "adverb", "pronoun", "numeral", "postposition",
       "conjunction", "question", "phrase", "other"}

# tag -> (page title, one-line description). Order = order on the index page.
TOPICS: dict[str, tuple[str, str]] = {
    "greetings":   ("Greetings and small talk", "Hello, goodbye, how are you, getting acquainted."),
    "family":      ("Family", "Relatives and family members."),
    "people":      ("People and professions", "Words for people, roles and professions."),
    "home":        ("Home and rooms", "Rooms, parts of the house, the building."),
    "furniture":   ("Furniture and household", "Things inside the house."),
    "city":        ("City and places", "Places you go to and come from."),
    "food":        ("Food", "Meals, dishes and things to eat."),
    "drinks":      ("Drinks", "Coffee, tea and other drinks."),
    "weather":     ("Weather", "Talking about the weather."),
    "seasons":     ("Seasons", "The four seasons and their forms."),
    "body":        ("Body", "Parts of the body, fingers."),
    "face":        ("Face", "Parts of the face and head."),
    "colours":     ("Colours", "Basic colours and colour compounds with -գույն."),
    "time":        ("Time", "Time of day, telling the time, soon and later."),
    "calendar":    ("Calendar", "Days of the week, months, dates, yesterday and tomorrow."),
    "numbers":     ("Numbers", "Cardinal and ordinal numerals."),
    "feelings":    ("Feelings and states", "How you feel: tired, glad, busy, sick…"),
    "countries":   ("Countries and nationalities", "Countries, nationalities and their adjectives."),
    "languages":   ("Languages", "Names of languages."),
    "transport":   ("Transport", "Getting around: by metro, by taxi, on foot."),
    "work":        ("Work", "Work, colleagues, meetings."),
    "travel":      ("Travel", "Trips, flights, staying somewhere."),
    "school":      ("Lessons and study", "Words about lessons, homework and studying."),
    "nature":      ("Nature", "Trees, mountains, animals, the outdoors."),
    "clothes":     ("Clothes and accessories", "Things you wear."),
    "abstract":    ("Abstract nouns", "Love, life, truth, success…"),
    "colloquial":  ("Colloquial and spoken", "Everyday spoken Armenian, slang and fillers."),
    "letters":     ("Letter practice words", "Example words used to practise individual letters in lessons 1–6."),
    "from-exercise": ("Words from exercises", "Vocabulary given in parentheses inside homework prompts."),
}
POS_PAGES: dict[str, tuple[str, str]] = {
    "verb":       ("All verbs", "Every verb in the base, in the infinitive."),
    "adjective":  ("All adjectives", "Every adjective in the base."),
    "phrase":     ("Phrases and expressions", "Multi-word expressions and set phrases."),
    "question":   ("Question words", "Who, what, where, when, why, how…"),
    "postposition": ("Postpositions", "for, about, with, on, under, near…"),
}

IGNORE_TAGS = {"vulgar"}  # kept on cards, no page of its own

ARM = "աբգդեզէըթժիլխծկհձղճմյնշոչպջռսվտրցուփքևօֆ"
ORDER = {ch: i for i, ch in enumerate(ARM)}


def sort_key(word: str) -> tuple:
    w = word.lower().lstrip("-")
    return tuple(ORDER.get(ch, 100 + ord(ch)) for ch in w)


def load() -> list[dict]:
    with DATA.open(encoding="utf-8", newline="") as f:
        reader = csv.reader(f, delimiter="\t", quoting=csv.QUOTE_NONE)
        header = next(reader)
        if [h.strip() for h in header] != COLS:
            sys.exit(f"{DATA}: unexpected header {header}")
        rows = []
        for n, raw in enumerate(reader, start=2):
            if not any(raw):
                continue
            if len(raw) != len(COLS):
                sys.exit(f"{DATA}:{n}: expected {len(COLS)} fields, got {len(raw)}")
            row = dict(zip(COLS, (v.strip() for v in raw)))
            row["_line"] = n
            rows.append(row)
    return rows


def validate(rows: list[dict]) -> None:
    ids = defaultdict(list)
    problems = []
    for r in rows:
        ids[r["id"]].append(r["_line"])
        if not r["lesson"].isdigit():
            problems.append(f"line {r['_line']}: lesson must be an integer, got {r['lesson']!r}")
        tags = [t.strip() for t in r["tags"].split(",") if t.strip()]
        if not tags or tags[0] not in POS:
            problems.append(f"line {r['_line']}: first tag must be a part of speech {sorted(POS)}, got {r['tags']!r}")
        if not r["hy"]:
            problems.append(f"line {r['_line']}: empty hy")
    for i, lines in ids.items():
        if len(lines) > 1:
            problems.append(f"duplicate id {i} on lines {lines}")
    if problems:
        print("\n".join(problems), file=sys.stderr)
        sys.exit(1)


def esc(s: str) -> str:
    return s.replace("|", "\\|")


def table(rows: list[dict], with_lesson: bool = True) -> str:
    head = "| Armenian | English | Phrase |" + (" Lesson |" if with_lesson else "")
    sep = "|---|---|---|" + ("---|" if with_lesson else "")
    lines = [head, sep]
    for r in sorted(rows, key=lambda r: sort_key(r["hy"])):
        en = esc(r["en"])
        if r["note"]:
            en += f" *({esc(r['note'])})*"
        phrase = ""
        if r["phrase_hy"]:
            phrase = esc(r["phrase_hy"]) + (f" — {esc(r['phrase_en'])}" if r["phrase_en"] else "")
        line = f"| <span class=\"hy\">{esc(r['hy'])}</span> | {en} | {phrase} |"
        if with_lesson:
            line += f" {r['lesson']} |"
        lines.append(line)
    return "\n".join(lines)


def write(path: Path, text: str) -> None:
    path.write_text(text.rstrip() + "\n", encoding="utf-8")


def main() -> None:
    rows = load()
    validate(rows)
    OUT.mkdir(parents=True, exist_ok=True)

    # remove previously generated pages so renamed/removed topics disappear
    for p in OUT.glob("*.md"):
        if MARKER in p.read_text(encoding="utf-8"):
            p.unlink()

    by_tag: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        for t in {t.strip() for t in r["tags"].split(",") if t.strip()}:
            by_tag[t].append(r)

    topic_links = []
    for tag, (title, desc) in list(TOPICS.items()) + list(POS_PAGES.items()):
        words = by_tag.get(tag)
        if not words:
            continue
        page = OUT / f"{tag}.md"
        write(page, f"{MARKER}\n# {title}\n\n{desc} {len(words)} entries. Lesson numbers show where a word was introduced.\n\n{table(words)}\n")
        topic_links.append(f"- [{title}]({tag}.md) — {len(words)}")

    unknown = sorted(t for t in by_tag if t not in TOPICS and t not in POS_PAGES and t not in POS and t not in IGNORE_TAGS)
    index = [
        MARKER,
        "# Vocabulary",
        "",
        f"{len(rows)} words and expressions from the lessons, in Armenian alphabetical order. "
        "Use the site search for anything specific. The source of truth is `data/vocab.tsv`; "
        "these pages are generated from it by `scripts/build_vocab_pages.py`.",
        "",
        "## By topic",
        "",
        *topic_links,
        "",
        "## All words",
        "",
        table(rows),
    ]
    write(OUT / "index.md", "\n".join(index))
    print(f"vocabulary: {len(rows)} words, {len(topic_links)} topic pages")
    if unknown:
        print(f"note: tags without a topic page: {', '.join(unknown)}")


if __name__ == "__main__":
    main()
